name: calculator_camera
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ICON
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.12.0

  # BLOC
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  freezed_annotation: ^2.4.1

  # IMAGE PICKER
  uuid: ^4.5.0
  file_picker: 8.0.5
  image_picker: ^1.0.8
  google_mlkit_text_recognition: ^0.13.1

  # LOCAL STORAGE
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # OTHERS
  flutter_config: ^2.0.0
  connectivity_plus: ^6.0.3
  math_expressions: ^2.6.0
  permission_handler: ^11.3.1
  go_router: ^14.1.4

dev_dependencies:
  flutter_lints: ^2.0.0
  very_good_analysis: ^3.1.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator:
  freezed: ^2.5.2

flutter_config:
  path: ../

get_cli:
  sub_folder: false

flutter:
  assets:
    - assets/launcher_icon/
  uses-material-design: true
